Miilenco/stable

Gemfile, Gemfile.lock, app/controllers/horses_controller.rb, app/models/horse.rb, app/models/user.rb, app/views/horses/_form.html.erb, app/views/horses/index.html.erb, app/views/horses/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20250303152558_devise_create_users.rb, db/migrate/20250303153916_create_horses.rb, db/schema.rb, test/controllers/horses_controller_test.rb, test/models/horse_test.rb, test/models/user_test.rb
Create, new, index, added devise gem. Created horse and user model.
=> Model start

Gemfile, Gemfile.lock, db/seeds.rb
Seed file created using faker gem.
5 users, 20 horses randomly assigned to users.
=> Seed file created - 5 users, 20 horses

app/controllers/horses_controller.rb, app/views/horses/edit.html.erb, app/views/horses/index.html.erb, app/views/horses/show.html.erb, config/routes.rb
Show and edit controller routes and view pages. added links for create new horse, edit horse and also horse name is clickable
=> show and edit done

app/controllers/horses_controller.rb, app/views/horses/show.html.erb, config/routes.rb
Added delete in routers, controller, and on show page their is a delete link
=> delete action added

app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/currency_controller.js, app/views/horses/_form.html.erb
made changes to the _form partial for adding new horses - add basic styling, drop down age selector, and expandable text boxes.
created stimulus controller for currency input to dynamically prevent user from inputting incorrect symbols. Not currently working, so not in use, kept code to work on later
=> new horse form updated

app/models/booking.rb, db/migrate/20250304141043_create_bookings.rb, db/schema.rb, test/models/booking_test.rb
Generated model in rails
Added necessary validations to model file
=> Bookings model

app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/horses_controller.rb, app/controllers/pages_controller.rb, app/models/booking.rb, config/routes.rb, test/controllers/bookings_controller_test.rb
Generated controller and added the required crud actions
=> Bookings controller

app/views/horses/show.html.erb
=> added booking form to horse show page

app/controllers/bookings_controller.rb, app/models/booking.rb, app/models/horse.rb, app/views/bookings/_form.html.erb, app/views/bookings/show.html.erb, db/seeds.rb, test/controllers/horses_controller_test.rb
bunch of changes made to get the booking form working.
- users can now book horses taking them from the horse show page to the booking show page. 
- A user can see their own horses show page, but if they try to book they cannot, it raises an alert. 
- buttons added to navigate back to horses/bookings from booking show page
=> Booking form horse show fix

app/controllers/users_controller.rb, app/views/users/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb
users can view all of their horses and the horses are styled using bertys css styling
=> view all my horses done

app/controllers/bookings_controller.rb, app/controllers/horses_controller.rb, app/models/booking.rb, app/models/horse.rb, app/views/bookings/_form.html.erb, app/views/bookings/show.html.erb, db/seeds.rb, test/controllers/bookings_controller_test.rb, test/controllers/horses_controller_test.rb, test/fixtures/bookings.yml, test/fixtures/horses.yml, test/fixtures/users.yml
tried to generate some tests/fix some that werent working for controllers.
some work still need here, in particular in bookings controller
=> Controller tests

app/views/shared/_navbar.html.erb
As discussed:
- Stable centered In navbar
- Horse on left and stable redirect to home
- bookings on navbar next to profile icon
- profile icon drop down
- account details (placeholder)
- log out
=> Navbar changes

app/views/bookings/index.html.erb
removed button and link in cards and made whole card clickable
=> Clickable booking cards

app/javascript/controllers/datepicker_controller.js
fixed bug by allowing start date = end date in stim cont and adding 1 to duration
minor date format style changes
=> 0 booking duration bug fix

app/views/bookings/index.html.erb
Added duration (needed to add +1 to end date - start date as horse can be booked for one day)
changed date format
minor stykle changes
=> Booking card date format and duration

app/views/shared/_navbar.html.erb
removed my horses from dropdown
added my horses and new horse to navbar
fixed bookings button bug
=> Adding buttons navbar

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss
changed the following colours to ones from our color scheme(s):
primary, secondary, also added a few shades of browns
=> Replacing bootstrap colour palette

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_global.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss
changed navbar and footer bg color and added faint margins
=> Navbar footer background color

app/assets/stylesheets/components/_global.scss, app/assets/stylesheets/components/_index.scss
=> Background color change

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/helpers/application_helper.rb, app/javascript/controllers/map_controller.js, app/models/horse.rb, app/views/horses/_info_window.html.erb, app/views/horses/show.html.erb, config/importmap.rb, config/initializers/geocoder.rb, db/migrate/20250306123613_add_coordinates_to_horses.rb, db/schema.rb
The logic of it is:
1) If a user is viewing their own horse then the booking form does not appear on the right, and instead a map will be on the right hand side. The edit and delete horse buttons are also visible in this view
2) If a user is viewing a different horse then the booking form is rendered on the right and the map is rendered on the bottom. The edit and delete horse buttons are hidden.
=> map show page

app/views/horses/index.html.erb
removed modal, made cards clickable
=> Index cards clickable

app/views/horses/index.html.erb
made basic quick view modal then filled with image and categories, basic styling
=> Quick view modal

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/views/horses/index.html.erb
added custom styling to modal button
=> Quick view button style

app/views/horses/index.html.erb
added a view details link to the bottom of the horse show modal
=> button added

app/views/horses/_photo_grid.html.erb, app/views/horses/show.html.erb
- created a grid of photos on the horse show page
- will add a modal carousel of images friday
=> Horse show page photo grid

app/views/horses/index.html.erb
OPEN TO DISCUSSION
Made several style changes here to see how they look, happy to discuss, but I think this gives a much cleaner look.
Details explained in commit messages
=> Remove location from horse index cards

app/views/horses/index.html.erb
Minor style/content changes.
details in commits
=> Horse modal info & styling

app/views/bookings/show.html.erb
added duration and total cost to show page
=> Booking show page total cost

app/models/booking.rb
The issue with booking form dates was a validation issue in model
=> changed validation method to allow end date to be same as start date

app/assets/stylesheets/components/_columns.scss, app/assets/stylesheets/components/_index.scss, app/views/horses/show.html.erb
made the booking form sticky
not sure if columns is the right name for css file and components was the right place for it but everything works
=> Booking form sticky

app/views/bookings/show.html.erb
=> Booking details background

app/views/bookings/index.html.erb
This is the new look
I've pushed this as changing the background of the `Sent Offers` and `Incoming Offers` doesn't seem to be as easy as I thought. Will not spend more time on it
=> Bookings index style change
